# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OntologyTool(object):
    def setupUi(self, OntologyTool):
        OntologyTool.setObjectName(_fromUtf8("OntologyTool"))
        OntologyTool.setWindowModality(QtCore.Qt.NonModal)
        OntologyTool.resize(968, 717)
        self.windowWidget = QtGui.QWidget(OntologyTool)
        self.windowWidget.setObjectName(_fromUtf8("windowWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.windowWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.toolSelectionWidget = QtGui.QWidget(self.windowWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolSelectionWidget.setFont(font)
        self.toolSelectionWidget.setStyleSheet(_fromUtf8("QWidget#toolSelectionWidget\n"
"{\n"
"  border:1px solid lightgrey;\n"
"}"))
        self.toolSelectionWidget.setObjectName(_fromUtf8("toolSelectionWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.toolSelectionWidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.toolSelectionLabel = QtGui.QLabel(self.toolSelectionWidget)
        self.toolSelectionLabel.setStyleSheet(_fromUtf8("border:none"))
        self.toolSelectionLabel.setObjectName(_fromUtf8("toolSelectionLabel"))
        self.gridLayout_3.addWidget(self.toolSelectionLabel, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.toolSelection = QtGui.QVBoxLayout()
        self.toolSelection.setObjectName(_fromUtf8("toolSelection"))
        self.radioSaturation = QtGui.QRadioButton(self.toolSelectionWidget)
        self.radioSaturation.setStyleSheet(_fromUtf8("border:none"))
        self.radioSaturation.setChecked(True)
        self.radioSaturation.setObjectName(_fromUtf8("radioSaturation"))
        self.toolSelection.addWidget(self.radioSaturation)
        self.radioFusion = QtGui.QRadioButton(self.toolSelectionWidget)
        self.radioFusion.setStyleSheet(_fromUtf8("border:none"))
        self.radioFusion.setObjectName(_fromUtf8("radioFusion"))
        self.toolSelection.addWidget(self.radioFusion)
        self.radioFusionAdv = QtGui.QRadioButton(self.toolSelectionWidget)
        self.radioFusionAdv.setStyleSheet(_fromUtf8("border:none"))
        self.radioFusionAdv.setObjectName(_fromUtf8("radioFusionAdv"))
        self.toolSelection.addWidget(self.radioFusionAdv)
        self.gridLayout_3.addLayout(self.toolSelection, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.toolSelectionWidget, 0, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.optionsToolWidget = QtGui.QWidget(self.windowWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.optionsToolWidget.sizePolicy().hasHeightForWidth())
        self.optionsToolWidget.setSizePolicy(sizePolicy)
        self.optionsToolWidget.setStyleSheet(_fromUtf8("QWidget#optionsToolWidget\n"
"{\n"
"  border:1px solid lightgrey;\n"
"}"))
        self.optionsToolWidget.setObjectName(_fromUtf8("optionsToolWidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.optionsToolWidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.rulesLayout = QtGui.QHBoxLayout()
        self.rulesLayout.setSpacing(0)
        self.rulesLayout.setObjectName(_fromUtf8("rulesLayout"))
        self.rulesFile = QtGui.QLineEdit(self.optionsToolWidget)
        self.rulesFile.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rulesFile.sizePolicy().hasHeightForWidth())
        self.rulesFile.setSizePolicy(sizePolicy)
        self.rulesFile.setStyleSheet(_fromUtf8(""))
        self.rulesFile.setDragEnabled(False)
        self.rulesFile.setObjectName(_fromUtf8("rulesFile"))
        self.rulesLayout.addWidget(self.rulesFile)
        self.browseRules_2 = QtGui.QPushButton(self.optionsToolWidget)
        self.browseRules_2.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseRules_2.sizePolicy().hasHeightForWidth())
        self.browseRules_2.setSizePolicy(sizePolicy)
        self.browseRules_2.setStyleSheet(_fromUtf8(""))
        self.browseRules_2.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/folder-search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browseRules_2.setIcon(icon)
        self.browseRules_2.setObjectName(_fromUtf8("browseRules_2"))
        self.rulesLayout.addWidget(self.browseRules_2)
        self.gridLayout_5.addLayout(self.rulesLayout, 1, 1, 1, 1)
        self.modeSelectedLabel = QtGui.QLabel(self.optionsToolWidget)
        self.modeSelectedLabel.setStyleSheet(_fromUtf8("border:none"))
        self.modeSelectedLabel.setObjectName(_fromUtf8("modeSelectedLabel"))
        self.gridLayout_5.addWidget(self.modeSelectedLabel, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.inputLayout = QtGui.QHBoxLayout()
        self.inputLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.inputLayout.setSpacing(0)
        self.inputLayout.setObjectName(_fromUtf8("inputLayout"))
        self.ontologyFiles = QtGui.QLineEdit(self.optionsToolWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ontologyFiles.sizePolicy().hasHeightForWidth())
        self.ontologyFiles.setSizePolicy(sizePolicy)
        self.ontologyFiles.setBaseSize(QtCore.QSize(0, 0))
        self.ontologyFiles.setStyleSheet(_fromUtf8(""))
        self.ontologyFiles.setDragEnabled(False)
        self.ontologyFiles.setObjectName(_fromUtf8("ontologyFiles"))
        self.inputLayout.addWidget(self.ontologyFiles)
        self.browseOntologies = QtGui.QPushButton(self.optionsToolWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseOntologies.sizePolicy().hasHeightForWidth())
        self.browseOntologies.setSizePolicy(sizePolicy)
        self.browseOntologies.setStyleSheet(_fromUtf8(""))
        self.browseOntologies.setText(_fromUtf8(""))
        self.browseOntologies.setIcon(icon)
        self.browseOntologies.setObjectName(_fromUtf8("browseOntologies"))
        self.inputLayout.addWidget(self.browseOntologies)
        self.horizontalLayout_2.addLayout(self.inputLayout)
        self.outputLayout = QtGui.QHBoxLayout()
        self.outputLayout.setSpacing(0)
        self.outputLayout.setObjectName(_fromUtf8("outputLayout"))
        self.outputName = QtGui.QLineEdit(self.optionsToolWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputName.sizePolicy().hasHeightForWidth())
        self.outputName.setSizePolicy(sizePolicy)
        self.outputName.setStyleSheet(_fromUtf8(""))
        self.outputName.setDragEnabled(False)
        self.outputName.setObjectName(_fromUtf8("outputName"))
        self.outputLayout.addWidget(self.outputName)
        self.browseOutput = QtGui.QPushButton(self.optionsToolWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browseOutput.sizePolicy().hasHeightForWidth())
        self.browseOutput.setSizePolicy(sizePolicy)
        self.browseOutput.setStyleSheet(_fromUtf8(""))
        self.browseOutput.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Save-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browseOutput.setIcon(icon1)
        self.browseOutput.setObjectName(_fromUtf8("browseOutput"))
        self.outputLayout.addWidget(self.browseOutput)
        self.horizontalLayout_2.addLayout(self.outputLayout)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.widget = QtGui.QWidget(self.optionsToolWidget)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.goButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goButton.sizePolicy().hasHeightForWidth())
        self.goButton.setSizePolicy(sizePolicy)
        self.goButton.setObjectName(_fromUtf8("goButton"))
        self.horizontalLayout_8.addWidget(self.goButton, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.stopButton = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setStyleSheet(_fromUtf8("border:none"))
        self.stopButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/stop-icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setIconSize(QtCore.QSize(28, 28))
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout_8.addWidget(self.stopButton, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.gridLayout_5.addWidget(self.widget, 2, 0, 1, 2)
        self.horizontalLayout.addWidget(self.optionsToolWidget)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.listViewWidget = QtGui.QWidget(self.windowWidget)
        self.listViewWidget.setObjectName(_fromUtf8("listViewWidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.listViewWidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(self.listViewWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 664, 496))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_6 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.sortieConsole = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.sortieConsole.setStyleSheet(_fromUtf8(""))
        self.sortieConsole.setReadOnly(True)
        self.sortieConsole.setObjectName(_fromUtf8("sortieConsole"))
        self.gridLayout_6.addWidget(self.sortieConsole, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableWidget = QtGui.QTableWidget(self.listViewWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget, QtCore.Qt.AlignLeft)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.listViewWidget, 1, 0, 1, 2)
        OntologyTool.setCentralWidget(self.windowWidget)
        self.menubar = QtGui.QMenuBar(OntologyTool)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 968, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        OntologyTool.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(OntologyTool)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        OntologyTool.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(OntologyTool)
        self.actionExit.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(OntologyTool)
        QtCore.QMetaObject.connectSlotsByName(OntologyTool)

    def retranslateUi(self, OntologyTool):
        OntologyTool.setWindowTitle(_translate("OntologyTool", "Ontology Tool", None))
        self.toolSelectionLabel.setText(_translate("OntologyTool", "Tool selection", None))
        self.radioSaturation.setToolTip(_translate("OntologyTool", "<html><head/><body><p><span style=\" color:#000000;\">Saturate a ontology with</span></p><p><span style=\" color:#000000;\">a list of rules in SPARQL</span><br/></p></body></html>", None))
        self.radioSaturation.setText(_translate("OntologyTool", "Saturation", None))
        self.radioFusion.setToolTip(_translate("OntologyTool", "<html><head/><body><p><span style=\" color:#000000;\">Merge ontologies into</span></p><p><span style=\" color:#000000;\">a output file</span></p></body></html>", None))
        self.radioFusion.setText(_translate("OntologyTool", "Fusion", None))
        self.radioFusionAdv.setToolTip(_translate("OntologyTool", "<html><head/><body><p><span style=\" color:#000000;\">Merge 2 ontologies</span></p><p><span style=\" color:#000000;\">with advanced controls</span></p><p><span style=\" color:#000000;\">(adding, removing triples)</span></p></body></html>", None))
        self.radioFusionAdv.setText(_translate("OntologyTool", "Fusion advanced", None))
        self.rulesFile.setToolTip(_translate("OntologyTool", "<html><head/><body><p>Put your file containing</p><p>the rules in SPARQL here</p></body></html>", None))
        self.rulesFile.setPlaceholderText(_translate("OntologyTool", "Rules file...", None))
        self.browseRules_2.setToolTip(_translate("OntologyTool", "<html><head/><body><p>Browse rules file</p></body></html>", None))
        self.modeSelectedLabel.setText(_translate("OntologyTool", "Saturation", None))
        self.ontologyFiles.setToolTip(_translate("OntologyTool", "<html><head/><body><p>Put your input ontology(ies)</p><p>here. You can input any kind of </p><p>format (.rdf, .ttl, .owl)</p></body></html>", None))
        self.ontologyFiles.setPlaceholderText(_translate("OntologyTool", "Ontology file(s)...", None))
        self.browseOntologies.setToolTip(_translate("OntologyTool", "<html><head/><body><p>Browse input files</p></body></html>", None))
        self.outputName.setToolTip(_translate("OntologyTool", "<html><head/><body><p>Put the output name of</p><p>the file here. You can add</p><p>the extension .rdf or .ttl</p></body></html>", None))
        self.outputName.setPlaceholderText(_translate("OntologyTool", "Output file...", None))
        self.browseOutput.setToolTip(_translate("OntologyTool", "<html><head/><body><p>Browse output file</p></body></html>", None))
        self.goButton.setToolTip(_translate("OntologyTool", "<html><head/><body><p>Launch the tool</p></body></html>", None))
        self.goButton.setText(_translate("OntologyTool", "GO !", None))
        self.stopButton.setToolTip(_translate("OntologyTool", "<html><head/><body><p>Stop the tool</p></body></html>", None))
        self.menuFile.setTitle(_translate("OntologyTool", "File", None))
        self.actionExit.setText(_translate("OntologyTool", "Exit", None))
        self.actionExit.setShortcut(_translate("OntologyTool", "Ctrl+Q", None))

import Images_rc
